version: '3.1'

services:
  
  reader:
    build: .
    restart: always
    environment:
      COV_STATUS_URL: "http://cov.dell.r57/status_read"
      MQTT_BROKER: "mqtt://mosquitto"
  
  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"